@startuml


start
:посмотреть доступных
          животных;
->

if (подать заявку на усыновление?) then (Да)
:заявка подана;

else( Нет)
endif
stop

@enduml

@startuml


start
:посмотреть список\nживотных;

->

if (добавить животное в базу?) then (Да  )
  :заполнить информацию о\nживотном;
  :животное добавлено в\nбазу для усыновления;
else (Нет)
  :удалить животное из списка;
  :животное удалено из\nсписка;
endif

stop

@enduml